// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package payload

import (
	negative "ad-service/internal/infrastructure/adapter/ad/negative"
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA8a797f8DecodeAdServiceInternalInfrastructureAdapterAdPayload(in *jlexer.Lexer, out *Advertisement) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "category":
			out.Category = string(in.String())
		case "author_id":
			out.AuthorID = string(in.String())
		case "price":
			out.Price = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "cached_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CachedAt).UnmarshalJSON(data))
			}
		case "negative":
			easyjsonA8a797f8DecodeAdServiceInternalInfrastructureAdapterAdNegative(in, &out.Negative)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA8a797f8EncodeAdServiceInternalInfrastructureAdapterAdPayload(out *jwriter.Writer, in Advertisement) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"author_id\":"
		out.RawString(prefix)
		out.String(string(in.AuthorID))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.String(string(in.Price))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"cached_at\":"
		out.RawString(prefix)
		out.Raw((in.CachedAt).MarshalJSON())
	}
	if true {
		const prefix string = ",\"negative\":"
		out.RawString(prefix)
		easyjsonA8a797f8EncodeAdServiceInternalInfrastructureAdapterAdNegative(out, in.Negative)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Advertisement) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA8a797f8EncodeAdServiceInternalInfrastructureAdapterAdPayload(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Advertisement) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA8a797f8EncodeAdServiceInternalInfrastructureAdapterAdPayload(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Advertisement) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA8a797f8DecodeAdServiceInternalInfrastructureAdapterAdPayload(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Advertisement) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA8a797f8DecodeAdServiceInternalInfrastructureAdapterAdPayload(l, v)
}
func easyjsonA8a797f8DecodeAdServiceInternalInfrastructureAdapterAdNegative(in *jlexer.Lexer, out *negative.Payload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = int(in.Int())
		case "classification":
			out.Classification = string(in.String())
		case "message":
			out.Message = string(in.String())
		case "base_message":
			out.BaseMessage = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA8a797f8EncodeAdServiceInternalInfrastructureAdapterAdNegative(out *jwriter.Writer, in negative.Payload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"classification\":"
		out.RawString(prefix)
		out.String(string(in.Classification))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"base_message\":"
		out.RawString(prefix)
		out.String(string(in.BaseMessage))
	}
	out.RawByte('}')
}
