services:
###########################################
#             APPLICATION                 #
###########################################

  # gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: build/Dockerfile
    environment:
      - HTTP_PORT=8080
      - ADMIN_HTTP_PORT=8081
      - GRPC_PORT=7002
      - ORDER_SERVICE_ADDR=order-service:7002
      - AD_SERVICE_ADDR=ad-service:7002
    depends_on:
      - order-service
      - ad-service
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    healthcheck:
      test: ["CMD-SHELL", "/etc/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
       - ./deploy/scripts/api-gateway-probes.sh:/etc/healthcheck.sh:ro
    labels:
      - autoheal=true
    networks:
      - app-network

  # order service
  order-service:
    build:
      context: ./services/order-service
      dockerfile: build/Dockerfile
    environment:
      - HTTP_PORT=8080
      - GRPC_PORT=7002
    ports:
      - "7001:7002"
      - "8081:8080"
    depends_on:
      kafka:
        condition: service_healthy
        restart: true
      order-service-migrations:
        condition: service_completed_successfully
        restart: true
    networks:
      - app-network

  # advertisement service
  ad-service:
    build:
      context: ./services/ad-service
      dockerfile: build/Dockerfile
    environment:
      - HTTP_PORT=8080
      - GRPC_PORT=7002
      - REVIEW_SERVICE_ADDR=review-service:7002
    ports:
      - "7002:7002"
      - "8082:8080"
    depends_on:
      review-service:
        condition: service_started
        restart: true
      ad-service-migrations:
        condition: service_completed_successfully
        restart: true
    networks:
      - app-network

  #review service
  review-service:
    build:
      context: ./services/review-service
      dockerfile: build/Dockerfile
    environment:
      - HTTP_PORT=8080
      - GRPC_PORT=7002
    ports:
      - "7004:7002"
      - "8084:8080"
    networks:
      - app-network

  # payment service
  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: build/Dockerfile
    environment:
      - HTTP_PORT=8080
      - GRPC_PORT=7002
    deploy:
      replicas: 3
    depends_on:
      etcd:
        condition: service_healthy
        restart: true
      kafka:
        condition: service_healthy
        restart: true
      payment-service-migrations:
        condition: service_completed_successfully
        restart: true
    networks:
      - app-network



###########################################
#             INFRASTRUCTURE              #
###########################################
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api-gateway:
        condition: service_started
        restart: true
    networks:
     - app-network

  autoheal:
    image: willfarrell/autoheal:1.2.0 # Use a specific version, e.g., 1.2.0
    restart: unless-stopped
    # Mount the Docker socket to allow autoheal to interact with the Docker daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Optional: Configure autoheal behavior via environment variables
    environment:
      # Watch only containers with the label autoheal=true (default setting)
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      # Set to "all" to monitor all containers without a specific label
      # - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=5 # Check every 5 seconds

  etcd:
    image: quay.io/coreos/etcd:v3.5.7
    container_name: etcd
    environment:
      - ETCD_NAME=etcd0
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health", "--endpoints=http://localhost:2379" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    ports:
      - "2379:2379" # client port
      - "2380:2380" # peer port
    networks:
        - app-network


  ###########################################
#             DATABASES                   #
###########################################

  order-postgres:
    image: postgres:15.10
    hostname: order-postgres
    restart: always
    environment:
      POSTGRES_DB: "orders"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "orders", "-U", "postgres" ]
      interval: 1s
      timeout: 2s
      retries: 5
    networks:
      - app-network

  ad-postgres:
    image: postgres:15.10
    hostname: ad-postgres
    restart: always
    environment:
      POSTGRES_DB: "advertisements"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "advertisements", "-U", "postgres" ]
      interval: 1s
      timeout: 2s
      retries: 5
    networks:
      - app-network

  payment-postgres:
    image: postgres:15.10
    hostname: payment-postgres
    restart: always
    environment:
      POSTGRES_DB: "payments"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "payments", "-U", "postgres" ]
      interval: 1s
      timeout: 2s
      retries: 5
    networks:
      - app-network

###########################################
#             MIGRATIONS                  #
###########################################
  payment-service-migrations:
    build:
      context: ./services/payment-service
      dockerfile: build/Dockerfile.migrations
      target: migrations
    container_name: payment-service-migrations
    environment:
      DB_NAME: payments
      DB_USER: postgres
      DB_HOST: payment-postgres
      DB_PORT: 5432
    command: [ "make", "migrations-up" ]
    depends_on:
      payment-postgres:
        condition: service_healthy
        restart: true
    restart: on-failure
    networks:
      - app-network

  order-service-migrations:
    build:
      context: ./services/order-service
      dockerfile: build/Dockerfile.migrations
      target: migrations
    container_name: order-service-migrations
    environment:
      DB_NAME: orders
      DB_USER: postgres
      DB_HOST: order-postgres
      DB_PORT: 5432
    command: [ "make", "migrations-up" ]
    depends_on:
      order-postgres:
        condition: service_healthy
        restart: true
    restart: on-failure
    networks:
      - app-network

  ad-service-migrations:
    build:
      context: ./services/ad-service
      dockerfile: build/Dockerfile.migrations
      target: migrations
    container_name: ad-service-migrations
    environment:
      DB_NAME: advertisements
      DB_USER: postgres
      DB_HOST: ad-postgres
      DB_PORT: 5432
    command: [ "make", "migrations-up" ]
    depends_on:
      ad-postgres:
        condition: service_healthy
        restart: true
    restart: on-failure
    networks:
      - app-network

###########################################
#             BROKERS                     #
###########################################

  akhq:
    image: tchiotludo/akhq:dev
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - "8090:8080"
    links:
      - kafka
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_C://0.0.0.0:9093,PLAINTEXT_L://0.0.0.0:9092,
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_L://kafka:9092,PLAINTEXT_C://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_L:PLAINTEXT,PLAINTEXT_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
    healthcheck:
      test: [ "CMD","kafka-topics","--bootstrap-server", "kafka:9092", "--list" ]
      interval: 1s
      timeout: 2s
      retries: 5
    networks:
      - app-network

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka
    entrypoint:
      - sh
      - -c
      - |
        echo "Waiting for Kafka..."
        until kafka-topics --bootstrap-server kafka:9092 --list; do
          sleep 1
        done

        echo "Creating topic order-events..."
        kafka-topics --bootstrap-server kafka:9092 --create --topic order-events --partitions 3 --replication-factor 1
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge