graceful:
  timeout: 5s

grpc_server:
  host: 0.0.0.0
  port: 7002
  max_connection_idle: 5m
  max_connection_age: 5m
  timeout: 5s
  time: 120m

http_server:
  port: 8080

postgres:
  host: ad-postgres
  port: 5432
  user: postgres
  password: "postgres"
  database: advertisements
  max_connections: 10
  min_connections: 3
  min_idle_connections: 3
  max_con_lifetime: 5s

services:
  blob: blob

circuit:
  handlers:
    - method: "/review_service.review.v1.ReviewService/GetAdReview"
      enabled: true
      max_requests: 10
      open_interval: 3s
      interval: 10s
      bucket_period: 1s
      threshold_consecutive: 5
      threshold_percentage: 30

hedge:
  handlers:
    - method: "/review_service.review.v1.ReviewService/GetAdReview"
      enabled: true
      window_size: 5  # Размер (100) кольцевого буфера последних 100 ответов. НО ДЛЯ ДЕМО СТАВЛЮ 5
      percentile: 0.95  # Целевой процентиль латентности, который оптимизируем (95-й)
      percentile_offset: 0.05 # Смещение вниз для запуска hedged-запроса чуть раньше
      budget: 1 # допускаю только 20% от всех запросов в качестве hedged. НО ДЛЯ ДЕМО СТАВЛЮ 100%
      reset_period: 1s # Сброс счётчиков раз в 1 секунду

rate_limit:
  rules:
    - clients: ["api-gateway"]
      handlers: ["/ad_service.ad.v1.AdService/GetAd"]
      limit: 5
      burst: 10
      timeout: 200ms
