graceful:
  timeout: 5s

grpc_server:
  host: 0.0.0.0
  port: 7003
  max_connection_idle: 5m
  max_connection_age: 5m
  timeout: 5s
  time: 120m

http_server:
  port: 8082

services:
  blob: blob


# Config for limit decrease
load_shedding:
  handlers:
    - method: "/review_service.review.v1.ReviewService/UnstableMethod"
      enabled: true
      limiter:
        window_size: 10
        min_window_time: 50ms
        max_window_time: 200ms
        min_rtt_threshold: 1ms
        max_backlog_size: 5       # уменьшить, чтобы очередь быстро переполнялась
        max_backlog_wait_time: 1s  # уменьшить, чтобы запросы быстрее дропались
      vegas:
        initial_max_inflight_limit: 50
        max_inflight_limit: 10000
        smoothing: 1.0      # мгновенные изменения лимита
        alpha_func_coefficient: 1
        beta_func_coefficient: 3
        rtt_no_load_probe_multiplier: 1

# Config for limit increase
#load_shedding:
#  handlers:
#    - method: "/review_service.review.v1.ReviewService/UnstableMethod"
#      enabled: true
#      limiter:
#        window_size: 60
#        min_window_time: 200ms
#        max_window_time: 5s
#        min_rtt_threshold: 10ms
#        max_backlog_size: 200
#        max_backlog_wait_time: 2s
#      vegas:
#        initial_max_inflight_limit: 3
#        max_inflight_limit: 50
#        smoothing: 0.5
#        rtt_no_load_probe_multiplier: 3
#        alpha_func_coefficient: 5
#        beta_func_coefficient: 20