graceful:
  timeout: 5s

grpc_server:
  host: 0.0.0.0
  port: 7003
  max_connection_idle: 5m
  max_connection_age: 5m
  timeout: 5s
  time: 120m

http_server:
  port: 8082

services:
  blob: blob

load_shedding:
  handlers:
    - method: "/review_service.review.v1.ReviewService/UnstableMethod"
      enabled: true
      limiter:
        window_size: 100               # маленькое окно, быстрый пересчёт
        min_window_time: 200ms
        max_window_time: 500ms
        min_rtt_threshold: 1ms        # учитывать все запросы
        max_backlog_size: 1000         # очередь, чтобы Vegas видел переполнение
        max_backlog_wait_time: 2s
      vegas:
        initial_max_inflight_limit: 20  # стартуем с небольшого лимита
        max_inflight_limit: 10000         # верхняя граница роста
        smoothing: 1.0                 # достаточно быстро реагируем на падение
        alpha_func_coefficient: 3      # рост умеренный
        beta_func_coefficient: 6      # падение агрессивное
        rtt_no_load_probe_multiplier: 1