// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/gofrs/uuid"
	"github.com/lib/pq"
)

// Order represents a row from 'public.order'.
type Order struct {
	OrderID        uuid.UUID   `db:"order_id" json:"order_id"`               // order_id
	IdempotencyKey uuid.UUID   `db:"idempotency_key" json:"idempotency_key"` // idempotency_key
	Status         string      `db:"status" json:"status"`                   // status
	ClientID       uuid.UUID   `db:"client_id" json:"client_id"`             // client_id
	Price          float64     `db:"price" json:"price"`                     // price
	AdID           uuid.UUID   `db:"ad_id" json:"ad_id"`                     // ad_id
	Category       string      `db:"category" json:"category"`               // category
	DeletedAt      pq.NullTime `db:"deleted_at" json:"deleted_at"`           // deleted_at
	CreatedAt      time.Time   `db:"created_at" json:"created_at"`           // created_at
}

// zeroOrder zero value of dto
var zeroOrder = Order{}

// Constants that should be used when building where statements
const (
	Alias_Order                = "o"
	Table_Order_With_Alias     = "order AS o"
	Table_Order                = "order"
	Field_Order_OrderID        = "order_id"
	Field_Order_IdempotencyKey = "idempotency_key"
	Field_Order_Status         = "status"
	Field_Order_ClientID       = "client_id"
	Field_Order_Price          = "price"
	Field_Order_AdID           = "ad_id"
	Field_Order_Category       = "category"
	Field_Order_DeletedAt      = "deleted_at"
	Field_Order_CreatedAt      = "created_at"
)

func (t Order) SelectColumnsWithCoalesce() []string {
	return []string{
		fmt.Sprintf("COALESCE(o.order_id, %v) as order_id", zeroOrder.OrderID),
		fmt.Sprintf("COALESCE(o.idempotency_key, %v) as idempotency_key", zeroOrder.IdempotencyKey),
		fmt.Sprintf("COALESCE(o.status, '%v') as status", zeroOrder.Status),
		fmt.Sprintf("COALESCE(o.client_id, %v) as client_id", zeroOrder.ClientID),
		fmt.Sprintf("COALESCE(o.price, %v) as price", zeroOrder.Price),
		fmt.Sprintf("COALESCE(o.ad_id, %v) as ad_id", zeroOrder.AdID),
		fmt.Sprintf("COALESCE(o.category, '%v') as category", zeroOrder.Category),
		"o.deleted_at",
		fmt.Sprintf("COALESCE(o.created_at, '%v') as created_at", zeroOrder.CreatedAt.Format(time.RFC3339)),
	}
}

func (t Order) SelectColumns() []string {
	return []string{
		"o.order_id",
		"o.idempotency_key",
		"o.status",
		"o.client_id",
		"o.price",
		"o.ad_id",
		"o.category",
		"o.deleted_at",
		"o.created_at",
	}
}

func (t Order) Columns(without ...string) []string {
	var str = "order_id, idempotency_key, status, client_id, price, ad_id, category, deleted_at, created_at"
	for _, exc := range without {
		str = strings.Replace(str+", ", exc+", ", "", 1)
	}
	return strings.Split(strings.TrimRight(str, ", "), ", ")
}

func (t Order) WithTable(col string) string {
	return fmt.Sprintf("o.%s", col)
}

func (t Order) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroOrder)
}

func (t Order) Join(rightColumnTable string, leftColumnTable string) string {
	return fmt.Sprintf("order AS o ON o.%s = %s", rightColumnTable, leftColumnTable)
}

func (t *Order) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"order_id":        t.OrderID,
		"idempotency_key": t.IdempotencyKey,
		"status":          t.Status,
		"client_id":       t.ClientID,
		"price":           t.Price,
		"ad_id":           t.AdID,
		"category":        t.Category,
		"deleted_at":      t.DeletedAt,
		"created_at":      t.CreatedAt,
	}
}

func (t *Order) Values(colNames ...string) (vals []interface{}) {
	m := t.ToMap()
	if _, ok := m["updated_at"]; ok {
		m["updated_at"] = time.Now()
	}

	for _, v := range colNames {
		vals = append(vals, m[v])
	}

	return vals
}
