// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/gofrs/uuid"
)

// OrdersState represents a row from 'public.orders_state'.
type OrdersState struct {
	ClientID uuid.UUID `db:"client_id" json:"client_id"` // client_id
	Version  int       `db:"version" json:"version"`     // version
}

// zeroOrdersState zero value of dto
var zeroOrdersState = OrdersState{}

// Constants that should be used when building where statements
const (
	Alias_OrdersState            = "os"
	Table_OrdersState_With_Alias = "orders_state AS os"
	Table_OrdersState            = "orders_state"
	Field_OrdersState_ClientID   = "client_id"
	Field_OrdersState_Version    = "version"
)

func (t OrdersState) SelectColumnsWithCoalesce() []string {
	return []string{
		fmt.Sprintf("COALESCE(os.client_id, %v) as client_id", zeroOrdersState.ClientID),
		fmt.Sprintf("COALESCE(os.version, %v) as version", zeroOrdersState.Version),
	}
}

func (t OrdersState) SelectColumns() []string {
	return []string{
		"os.client_id",
		"os.version",
	}
}

func (t OrdersState) Columns(without ...string) []string {
	var str = "client_id, version"
	for _, exc := range without {
		str = strings.Replace(str+", ", exc+", ", "", 1)
	}
	return strings.Split(strings.TrimRight(str, ", "), ", ")
}

func (t OrdersState) WithTable(col string) string {
	return fmt.Sprintf("os.%s", col)
}

func (t OrdersState) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroOrdersState)
}

func (t OrdersState) Join(rightColumnTable string, leftColumnTable string) string {
	return fmt.Sprintf("orders_state AS os ON os.%s = %s", rightColumnTable, leftColumnTable)
}

func (t *OrdersState) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"client_id": t.ClientID,
		"version":   t.Version,
	}
}

func (t *OrdersState) Values(colNames ...string) (vals []interface{}) {
	m := t.ToMap()
	if _, ok := m["updated_at"]; ok {
		m["updated_at"] = time.Now()
	}

	for _, v := range colNames {
		vals = append(vals, m[v])
	}

	return vals
}
