// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: review-service/review/v1/review.proto

package reviewV1

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAdReviewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор
	AdId          string `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdReviewRequest) Reset() {
	*x = GetAdReviewRequest{}
	mi := &file_review_service_review_v1_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdReviewRequest) ProtoMessage() {}

func (x *GetAdReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_service_review_v1_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdReviewRequest.ProtoReflect.Descriptor instead.
func (*GetAdReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_service_review_v1_review_proto_rawDescGZIP(), []int{0}
}

func (x *GetAdReviewRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

type GetAdReviewResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Review        *GetAdReviewResponse_Review `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdReviewResponse) Reset() {
	*x = GetAdReviewResponse{}
	mi := &file_review_service_review_v1_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdReviewResponse) ProtoMessage() {}

func (x *GetAdReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_service_review_v1_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdReviewResponse.ProtoReflect.Descriptor instead.
func (*GetAdReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_service_review_v1_review_proto_rawDescGZIP(), []int{1}
}

func (x *GetAdReviewResponse) GetReview() *GetAdReviewResponse_Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type UnstableMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnstableMethodRequest) Reset() {
	*x = UnstableMethodRequest{}
	mi := &file_review_service_review_v1_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnstableMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnstableMethodRequest) ProtoMessage() {}

func (x *UnstableMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_service_review_v1_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnstableMethodRequest.ProtoReflect.Descriptor instead.
func (*UnstableMethodRequest) Descriptor() ([]byte, []int) {
	return file_review_service_review_v1_review_proto_rawDescGZIP(), []int{2}
}

type UnstableMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnstableMethodResponse) Reset() {
	*x = UnstableMethodResponse{}
	mi := &file_review_service_review_v1_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnstableMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnstableMethodResponse) ProtoMessage() {}

func (x *UnstableMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_service_review_v1_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnstableMethodResponse.ProtoReflect.Descriptor instead.
func (*UnstableMethodResponse) Descriptor() ([]byte, []int) {
	return file_review_service_review_v1_review_proto_rawDescGZIP(), []int{3}
}

type GetAdReviewResponse_Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvgReview     *decimal.Decimal       `protobuf:"bytes,1,opt,name=avg_review,json=avgReview,proto3" json:"avg_review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdReviewResponse_Review) Reset() {
	*x = GetAdReviewResponse_Review{}
	mi := &file_review_service_review_v1_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdReviewResponse_Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdReviewResponse_Review) ProtoMessage() {}

func (x *GetAdReviewResponse_Review) ProtoReflect() protoreflect.Message {
	mi := &file_review_service_review_v1_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdReviewResponse_Review.ProtoReflect.Descriptor instead.
func (*GetAdReviewResponse_Review) Descriptor() ([]byte, []int) {
	return file_review_service_review_v1_review_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetAdReviewResponse_Review) GetAvgReview() *decimal.Decimal {
	if x != nil {
		return x.AvgReview
	}
	return nil
}

var File_review_service_review_v1_review_proto protoreflect.FileDescriptor

const file_review_service_review_v1_review_proto_rawDesc = "" +
	"\n" +
	"%review-service/review/v1/review.proto\x12\x18review_service.review.v1\x1a\x19google/type/decimal.proto\")\n" +
	"\x12GetAdReviewRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\"\xa2\x01\n" +
	"\x13GetAdReviewResponse\x12L\n" +
	"\x06review\x18\x01 \x01(\v24.review_service.review.v1.GetAdReviewResponse.ReviewR\x06review\x1a=\n" +
	"\x06Review\x123\n" +
	"\n" +
	"avg_review\x18\x01 \x01(\v2\x14.google.type.DecimalR\tavgReview\"\x17\n" +
	"\x15UnstableMethodRequest\"\x18\n" +
	"\x16UnstableMethodResponse2\xf0\x01\n" +
	"\rReviewService\x12j\n" +
	"\vGetAdReview\x12,.review_service.review.v1.GetAdReviewRequest\x1a-.review_service.review.v1.GetAdReviewResponse\x12s\n" +
	"\x0eUnstableMethod\x12/.review_service.review.v1.UnstableMethodRequest\x1a0.review_service.review.v1.UnstableMethodResponseB\x1fZ\x1dreview/pkg/review/v1;reviewV1b\x06proto3"

var (
	file_review_service_review_v1_review_proto_rawDescOnce sync.Once
	file_review_service_review_v1_review_proto_rawDescData []byte
)

func file_review_service_review_v1_review_proto_rawDescGZIP() []byte {
	file_review_service_review_v1_review_proto_rawDescOnce.Do(func() {
		file_review_service_review_v1_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_service_review_v1_review_proto_rawDesc), len(file_review_service_review_v1_review_proto_rawDesc)))
	})
	return file_review_service_review_v1_review_proto_rawDescData
}

var file_review_service_review_v1_review_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_review_service_review_v1_review_proto_goTypes = []any{
	(*GetAdReviewRequest)(nil),         // 0: review_service.review.v1.GetAdReviewRequest
	(*GetAdReviewResponse)(nil),        // 1: review_service.review.v1.GetAdReviewResponse
	(*UnstableMethodRequest)(nil),      // 2: review_service.review.v1.UnstableMethodRequest
	(*UnstableMethodResponse)(nil),     // 3: review_service.review.v1.UnstableMethodResponse
	(*GetAdReviewResponse_Review)(nil), // 4: review_service.review.v1.GetAdReviewResponse.Review
	(*decimal.Decimal)(nil),            // 5: google.type.Decimal
}
var file_review_service_review_v1_review_proto_depIdxs = []int32{
	4, // 0: review_service.review.v1.GetAdReviewResponse.review:type_name -> review_service.review.v1.GetAdReviewResponse.Review
	5, // 1: review_service.review.v1.GetAdReviewResponse.Review.avg_review:type_name -> google.type.Decimal
	0, // 2: review_service.review.v1.ReviewService.GetAdReview:input_type -> review_service.review.v1.GetAdReviewRequest
	2, // 3: review_service.review.v1.ReviewService.UnstableMethod:input_type -> review_service.review.v1.UnstableMethodRequest
	1, // 4: review_service.review.v1.ReviewService.GetAdReview:output_type -> review_service.review.v1.GetAdReviewResponse
	3, // 5: review_service.review.v1.ReviewService.UnstableMethod:output_type -> review_service.review.v1.UnstableMethodResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_review_service_review_v1_review_proto_init() }
func file_review_service_review_v1_review_proto_init() {
	if File_review_service_review_v1_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_service_review_v1_review_proto_rawDesc), len(file_review_service_review_v1_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_service_review_v1_review_proto_goTypes,
		DependencyIndexes: file_review_service_review_v1_review_proto_depIdxs,
		MessageInfos:      file_review_service_review_v1_review_proto_msgTypes,
	}.Build()
	File_review_service_review_v1_review_proto = out.File
	file_review_service_review_v1_review_proto_goTypes = nil
	file_review_service_review_v1_review_proto_depIdxs = nil
}
