// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: review-service/review/v1/review.proto

package reviewV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReviewService_GetAdReview_FullMethodName    = "/review_service.review.v1.ReviewService/GetAdReview"
	ReviewService_UnstableMethod_FullMethodName = "/review_service.review.v1.ReviewService/UnstableMethod"
)

// ReviewServiceClient is the client API for ReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewServiceClient interface {
	// Получить отзыв по одному объявлению
	GetAdReview(ctx context.Context, in *GetAdReviewRequest, opts ...grpc.CallOption) (*GetAdReviewResponse, error)
	// Метод с ростом задержки
	UnstableMethod(ctx context.Context, in *UnstableMethodRequest, opts ...grpc.CallOption) (*UnstableMethodResponse, error)
}

type reviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewServiceClient(cc grpc.ClientConnInterface) ReviewServiceClient {
	return &reviewServiceClient{cc}
}

func (c *reviewServiceClient) GetAdReview(ctx context.Context, in *GetAdReviewRequest, opts ...grpc.CallOption) (*GetAdReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdReviewResponse)
	err := c.cc.Invoke(ctx, ReviewService_GetAdReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) UnstableMethod(ctx context.Context, in *UnstableMethodRequest, opts ...grpc.CallOption) (*UnstableMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnstableMethodResponse)
	err := c.cc.Invoke(ctx, ReviewService_UnstableMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewServiceServer is the server API for ReviewService service.
// All implementations should embed UnimplementedReviewServiceServer
// for forward compatibility.
type ReviewServiceServer interface {
	// Получить отзыв по одному объявлению
	GetAdReview(context.Context, *GetAdReviewRequest) (*GetAdReviewResponse, error)
	// Метод с ростом задержки
	UnstableMethod(context.Context, *UnstableMethodRequest) (*UnstableMethodResponse, error)
}

// UnimplementedReviewServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewServiceServer struct{}

func (UnimplementedReviewServiceServer) GetAdReview(context.Context, *GetAdReviewRequest) (*GetAdReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdReview not implemented")
}
func (UnimplementedReviewServiceServer) UnstableMethod(context.Context, *UnstableMethodRequest) (*UnstableMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnstableMethod not implemented")
}
func (UnimplementedReviewServiceServer) testEmbeddedByValue() {}

// UnsafeReviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewServiceServer will
// result in compilation errors.
type UnsafeReviewServiceServer interface {
	mustEmbedUnimplementedReviewServiceServer()
}

func RegisterReviewServiceServer(s grpc.ServiceRegistrar, srv ReviewServiceServer) {
	// If the following call panics, it indicates UnimplementedReviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReviewService_ServiceDesc, srv)
}

func _ReviewService_GetAdReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).GetAdReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewService_GetAdReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).GetAdReview(ctx, req.(*GetAdReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_UnstableMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnstableMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).UnstableMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewService_UnstableMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).UnstableMethod(ctx, req.(*UnstableMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewService_ServiceDesc is the grpc.ServiceDesc for ReviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "review_service.review.v1.ReviewService",
	HandlerType: (*ReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdReview",
			Handler:    _ReviewService_GetAdReview_Handler,
		},
		{
			MethodName: "UnstableMethod",
			Handler:    _ReviewService_UnstableMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review-service/review/v1/review.proto",
}
