// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api-gateway/ad/v1/ad.proto

package adV1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          string                 `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdRequest) Reset() {
	*x = GetAdRequest{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdRequest) ProtoMessage() {}

func (x *GetAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdRequest.ProtoReflect.Descriptor instead.
func (*GetAdRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{0}
}

func (x *GetAdRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

type GetAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *GetAdResponse_Ad      `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdResponse) Reset() {
	*x = GetAdResponse{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdResponse) ProtoMessage() {}

func (x *GetAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdResponse.ProtoReflect.Descriptor instead.
func (*GetAdResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{1}
}

func (x *GetAdResponse) GetAd() *GetAdResponse_Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type ListAdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdsRequest) Reset() {
	*x = ListAdsRequest{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsRequest) ProtoMessage() {}

func (x *ListAdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsRequest.ProtoReflect.Descriptor instead.
func (*ListAdsRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{2}
}

type ListAdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ads           []*ListAdsResponse_Ad  `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdsResponse) Reset() {
	*x = ListAdsResponse{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsResponse) ProtoMessage() {}

func (x *ListAdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsResponse.ProtoReflect.Descriptor instead.
func (*ListAdsResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{3}
}

func (x *ListAdsResponse) GetAds() []*ListAdsResponse_Ad {
	if x != nil {
		return x.Ads
	}
	return nil
}

type CreateAdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Заголовок
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Категория
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// ID автор
	AuthorId string `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// Цена
	Price         *money.Money `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdRequest) Reset() {
	*x = CreateAdRequest{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdRequest) ProtoMessage() {}

func (x *CreateAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdRequest.ProtoReflect.Descriptor instead.
func (*CreateAdRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAdRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateAdRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateAdRequest) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

type CreateAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *CreateAdResponse_Ad   `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdResponse) Reset() {
	*x = CreateAdResponse{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdResponse) ProtoMessage() {}

func (x *CreateAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdResponse.ProtoReflect.Descriptor instead.
func (*CreateAdResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAdResponse) GetAd() *CreateAdResponse_Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type DeactivateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateRequest) Reset() {
	*x = DeactivateRequest{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateRequest) ProtoMessage() {}

func (x *DeactivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateRequest.ProtoReflect.Descriptor instead.
func (*DeactivateRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{6}
}

func (x *DeactivateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeactivateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Статус (active, inactive)
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateResponse) Reset() {
	*x = DeactivateResponse{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateResponse) ProtoMessage() {}

func (x *DeactivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateResponse.ProtoReflect.Descriptor instead.
func (*DeactivateResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{7}
}

func (x *DeactivateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAdResponse_Ad struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // Уникальный идентификатор
	Title     string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                          // Заголовок
	Category  string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                    // Категория
	AuthorId  string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`    // ID автор
	Price     *money.Money           `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`                          // Цена
	Status    string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                        // Статус (active, sold, banned)
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Дата создания (ISO 8601)
	// Рейтинг по оценкам объявления
	Review        *GetAdResponse_Ad_AdReview `protobuf:"bytes,8,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdResponse_Ad) Reset() {
	*x = GetAdResponse_Ad{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdResponse_Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdResponse_Ad) ProtoMessage() {}

func (x *GetAdResponse_Ad) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdResponse_Ad.ProtoReflect.Descriptor instead.
func (*GetAdResponse_Ad) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetAdResponse_Ad) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAdResponse_Ad) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetAdResponse_Ad) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetAdResponse_Ad) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *GetAdResponse_Ad) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *GetAdResponse_Ad) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAdResponse_Ad) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetAdResponse_Ad) GetReview() *GetAdResponse_Ad_AdReview {
	if x != nil {
		return x.Review
	}
	return nil
}

type GetAdResponse_Ad_AdReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvgReview     *decimal.Decimal       `protobuf:"bytes,1,opt,name=avg_review,json=avgReview,proto3" json:"avg_review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdResponse_Ad_AdReview) Reset() {
	*x = GetAdResponse_Ad_AdReview{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdResponse_Ad_AdReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdResponse_Ad_AdReview) ProtoMessage() {}

func (x *GetAdResponse_Ad_AdReview) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdResponse_Ad_AdReview.ProtoReflect.Descriptor instead.
func (*GetAdResponse_Ad_AdReview) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *GetAdResponse_Ad_AdReview) GetAvgReview() *decimal.Decimal {
	if x != nil {
		return x.AvgReview
	}
	return nil
}

type ListAdsResponse_Ad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // Уникальный идентификатор
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                          // Заголовок
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`              // Описание
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`                    // Категория
	AuthorId      string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`    // ID автор
	Price         *money.Money           `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`                          // Цена
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                        // Статус (active, sold, banned)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Дата создания (ISO 8601)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdsResponse_Ad) Reset() {
	*x = ListAdsResponse_Ad{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdsResponse_Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsResponse_Ad) ProtoMessage() {}

func (x *ListAdsResponse_Ad) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsResponse_Ad.ProtoReflect.Descriptor instead.
func (*ListAdsResponse_Ad) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListAdsResponse_Ad) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *ListAdsResponse_Ad) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAdsResponse_Ad) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Уникальный идентификатор
type CreateAdResponse_Ad struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Статус (active, inactive, banned)
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdResponse_Ad) Reset() {
	*x = CreateAdResponse_Ad{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdResponse_Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdResponse_Ad) ProtoMessage() {}

func (x *CreateAdResponse_Ad) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdResponse_Ad.ProtoReflect.Descriptor instead.
func (*CreateAdResponse_Ad) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateAdResponse_Ad) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAdResponse_Ad) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_gateway_ad_v1_ad_proto protoreflect.FileDescriptor

const file_api_gateway_ad_v1_ad_proto_rawDesc = "" +
	"\n" +
	"\x1aapi-gateway/ad/v1/ad.proto\x12\x11api_gateway.ad.v1\x1a\x17google/type/money.proto\x1a\x19google/type/decimal.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"#\n" +
	"\fGetAdRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\"\xae\x03\n" +
	"\rGetAdResponse\x123\n" +
	"\x02ad\x18\x01 \x01(\v2#.api_gateway.ad.v1.GetAdResponse.AdR\x02ad\x1a\xe7\x02\n" +
	"\x02Ad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12(\n" +
	"\x05price\x18\x05 \x01(\v2\x12.google.type.MoneyR\x05price\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12D\n" +
	"\x06review\x18\b \x01(\v2,.api_gateway.ad.v1.GetAdResponse.Ad.AdReviewR\x06review\x1a?\n" +
	"\bAdReview\x123\n" +
	"\n" +
	"avg_review\x18\x01 \x01(\v2\x14.google.type.DecimalR\tavgReview\"\x10\n" +
	"\x0eListAdsRequest\"\xcf\x02\n" +
	"\x0fListAdsResponse\x127\n" +
	"\x03ads\x18\x01 \x03(\v2%.api_gateway.ad.v1.ListAdsResponse.AdR\x03ads\x1a\x82\x02\n" +
	"\x02Ad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\x12(\n" +
	"\x05price\x18\x06 \x01(\v2\x12.google.type.MoneyR\x05price\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8a\x01\n" +
	"\x0fCreateAdRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12(\n" +
	"\x05price\x18\x04 \x01(\v2\x12.google.type.MoneyR\x05price\"x\n" +
	"\x10CreateAdResponse\x126\n" +
	"\x02ad\x18\x01 \x01(\v2&.api_gateway.ad.v1.CreateAdResponse.AdR\x02ad\x1a,\n" +
	"\x02Ad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"#\n" +
	"\x11DeactivateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x12DeactivateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xb9\x03\n" +
	"\tAdService\x12Z\n" +
	"\x05GetAd\x12\x1f.api_gateway.ad.v1.GetAdRequest\x1a .api_gateway.ad.v1.GetAdResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/v1/ad\x12a\n" +
	"\aListAds\x12!.api_gateway.ad.v1.ListAdsRequest\x1a\".api_gateway.ad.v1.ListAdsResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/v1/ads\x12c\n" +
	"\bCreateAd\x12\".api_gateway.ad.v1.CreateAdRequest\x1a#.api_gateway.ad.v1.CreateAdResponse\"\x0e\x82\xd3\xe4\x93\x02\b\"\x06/v1/ad\x12t\n" +
	"\n" +
	"Deactivate\x12$.api_gateway.ad.v1.DeactivateRequest\x1a%.api_gateway.ad.v1.DeactivateResponse\"\x19\x82\xd3\xe4\x93\x02\x13\"\x11/v1/ad/deactivate\x1a\x12\x92A\x0f\n" +
	"\radvertisementBP\x92A1\x12/\n" +
	"\rAdvertisement\x12\x19Advertisement application2\x031.0Z\x1aapi_gateway/pkg/ad/v1;adV1b\x06proto3"

var (
	file_api_gateway_ad_v1_ad_proto_rawDescOnce sync.Once
	file_api_gateway_ad_v1_ad_proto_rawDescData []byte
)

func file_api_gateway_ad_v1_ad_proto_rawDescGZIP() []byte {
	file_api_gateway_ad_v1_ad_proto_rawDescOnce.Do(func() {
		file_api_gateway_ad_v1_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_ad_v1_ad_proto_rawDesc), len(file_api_gateway_ad_v1_ad_proto_rawDesc)))
	})
	return file_api_gateway_ad_v1_ad_proto_rawDescData
}

var file_api_gateway_ad_v1_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_gateway_ad_v1_ad_proto_goTypes = []any{
	(*GetAdRequest)(nil),              // 0: api_gateway.ad.v1.GetAdRequest
	(*GetAdResponse)(nil),             // 1: api_gateway.ad.v1.GetAdResponse
	(*ListAdsRequest)(nil),            // 2: api_gateway.ad.v1.ListAdsRequest
	(*ListAdsResponse)(nil),           // 3: api_gateway.ad.v1.ListAdsResponse
	(*CreateAdRequest)(nil),           // 4: api_gateway.ad.v1.CreateAdRequest
	(*CreateAdResponse)(nil),          // 5: api_gateway.ad.v1.CreateAdResponse
	(*DeactivateRequest)(nil),         // 6: api_gateway.ad.v1.DeactivateRequest
	(*DeactivateResponse)(nil),        // 7: api_gateway.ad.v1.DeactivateResponse
	(*GetAdResponse_Ad)(nil),          // 8: api_gateway.ad.v1.GetAdResponse.Ad
	(*GetAdResponse_Ad_AdReview)(nil), // 9: api_gateway.ad.v1.GetAdResponse.Ad.AdReview
	(*ListAdsResponse_Ad)(nil),        // 10: api_gateway.ad.v1.ListAdsResponse.Ad
	(*CreateAdResponse_Ad)(nil),       // 11: api_gateway.ad.v1.CreateAdResponse.Ad
	(*money.Money)(nil),               // 12: google.type.Money
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
	(*decimal.Decimal)(nil),           // 14: google.type.Decimal
}
var file_api_gateway_ad_v1_ad_proto_depIdxs = []int32{
	8,  // 0: api_gateway.ad.v1.GetAdResponse.ad:type_name -> api_gateway.ad.v1.GetAdResponse.Ad
	10, // 1: api_gateway.ad.v1.ListAdsResponse.ads:type_name -> api_gateway.ad.v1.ListAdsResponse.Ad
	12, // 2: api_gateway.ad.v1.CreateAdRequest.price:type_name -> google.type.Money
	11, // 3: api_gateway.ad.v1.CreateAdResponse.ad:type_name -> api_gateway.ad.v1.CreateAdResponse.Ad
	12, // 4: api_gateway.ad.v1.GetAdResponse.Ad.price:type_name -> google.type.Money
	13, // 5: api_gateway.ad.v1.GetAdResponse.Ad.created_at:type_name -> google.protobuf.Timestamp
	9,  // 6: api_gateway.ad.v1.GetAdResponse.Ad.review:type_name -> api_gateway.ad.v1.GetAdResponse.Ad.AdReview
	14, // 7: api_gateway.ad.v1.GetAdResponse.Ad.AdReview.avg_review:type_name -> google.type.Decimal
	12, // 8: api_gateway.ad.v1.ListAdsResponse.Ad.price:type_name -> google.type.Money
	13, // 9: api_gateway.ad.v1.ListAdsResponse.Ad.created_at:type_name -> google.protobuf.Timestamp
	0,  // 10: api_gateway.ad.v1.AdService.GetAd:input_type -> api_gateway.ad.v1.GetAdRequest
	2,  // 11: api_gateway.ad.v1.AdService.ListAds:input_type -> api_gateway.ad.v1.ListAdsRequest
	4,  // 12: api_gateway.ad.v1.AdService.CreateAd:input_type -> api_gateway.ad.v1.CreateAdRequest
	6,  // 13: api_gateway.ad.v1.AdService.Deactivate:input_type -> api_gateway.ad.v1.DeactivateRequest
	1,  // 14: api_gateway.ad.v1.AdService.GetAd:output_type -> api_gateway.ad.v1.GetAdResponse
	3,  // 15: api_gateway.ad.v1.AdService.ListAds:output_type -> api_gateway.ad.v1.ListAdsResponse
	5,  // 16: api_gateway.ad.v1.AdService.CreateAd:output_type -> api_gateway.ad.v1.CreateAdResponse
	7,  // 17: api_gateway.ad.v1.AdService.Deactivate:output_type -> api_gateway.ad.v1.DeactivateResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_gateway_ad_v1_ad_proto_init() }
func file_api_gateway_ad_v1_ad_proto_init() {
	if File_api_gateway_ad_v1_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_ad_v1_ad_proto_rawDesc), len(file_api_gateway_ad_v1_ad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_ad_v1_ad_proto_goTypes,
		DependencyIndexes: file_api_gateway_ad_v1_ad_proto_depIdxs,
		MessageInfos:      file_api_gateway_ad_v1_ad_proto_msgTypes,
	}.Build()
	File_api_gateway_ad_v1_ad_proto = out.File
	file_api_gateway_ad_v1_ad_proto_goTypes = nil
	file_api_gateway_ad_v1_ad_proto_depIdxs = nil
}
