graceful:
  timeout: 5s

grpc_server:
  host: 0.0.0.0
  port: 7008
  max_connection_idle: 5m
  max_connection_age: 5m
  timeout: 5s
  time: 120m

http_server:
  port: 8080

kafka:
  brokers: [ "kafka:9092" ]
  consumer_group: payment-service-payment-events

etcd:
  endpoints: [ "etcd:2379" ]
  dial_timeout: 5s

leader_election:
  key: "/services/payment-service/inbox/leader"

inbox:
  config:
    messages_limit: 1000
    max_err_count_for_message: 5
    normal_messages_poll_interval: 2s
    error_messages_poll_interval: 10s

  topics:
    order-events:
      batch_size: 100

postgres:
  host: payment-postgres
  port: 5432
  user: postgres
  password: "postgres"
  database: payments
  max_connections: 10
  min_connections: 3
  min_idle_connections: 3
  max_con_lifetime: 5s

