// Code generated by protoc-gen-goclay. DO NOT EDIT.

package adV1

import (
	context "context"
	_ "embed"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	transport "github.com/not-for-prod/clay/transport"
	httptransport "github.com/not-for-prod/clay/transport/httptransport"
	grpc "google.golang.org/grpc"
)

//go:generate implgen --src ad_grpc.pb.go --interface-name AdServiceServer --dst ../../../.

//go:embed ad.swagger.json
var Swagger []byte

// AdServiceServiceDesc is a descriptor/registrator for the AdServiceServer.
type AdServiceServiceDesc struct {
	svc  AdServiceServer
	opts httptransport.DescOptions
}

// NewAdServiceServiceDesc creates new registrator for the AdServiceServer.
// It implements httptransport.ConfigurableServiceDesc as well.
func NewAdServiceServiceDesc(i AdServiceServer) *AdServiceServiceDesc {
	return &AdServiceServiceDesc{svc: i}
}

// RegisterGRPC implements service registrator interface.
func (d *AdServiceServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterAdServiceServer(s, d.svc)
}

// Apply applies passed options.
func (d *AdServiceServiceDesc) Apply(oo ...transport.DescOption) {
	for _, o := range oo {
		o.Apply(&d.opts)
	}
}

// SwaggerDef returns this file's Swagger definition.
func (d *AdServiceServiceDesc) SwaggerDef() []byte {
	return Swagger
}

// RegisterHTTP registers this service's HTTP handlers/bindings.
func (w *AdServiceServiceDesc) RegisterHTTP(
	ctx context.Context,
	mux *runtime.ServeMux,
) error {
	return RegisterAdServiceHandlerServer(ctx, mux, w)
}

// Wrap all http methods with interceptor support

func (w *AdServiceServiceDesc) ListAds(ctx context.Context, in *ListAdsRequest) (*ListAdsResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.ListAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/ad_service.ad.v1.AdService/ListAds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.ListAds(ctx, req.(*ListAdsRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*ListAdsResponse), err
}

func (w *AdServiceServiceDesc) GetAd(ctx context.Context, in *GetAdRequest) (*GetAdResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.GetAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/ad_service.ad.v1.AdService/GetAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.GetAd(ctx, req.(*GetAdRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*GetAdResponse), err
}

func (w *AdServiceServiceDesc) CreateAd(ctx context.Context, in *CreateAdRequest) (*CreateAdResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.CreateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/ad_service.ad.v1.AdService/CreateAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.CreateAd(ctx, req.(*CreateAdRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*CreateAdResponse), err
}

func (w *AdServiceServiceDesc) Deactivate(ctx context.Context, in *DeactivateRequest) (*DeactivateResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.Deactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/ad_service.ad.v1.AdService/Deactivate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.Deactivate(ctx, req.(*DeactivateRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*DeactivateResponse), err
}
