// Code generated by protoc-gen-goclay. DO NOT EDIT.

package orderV1

import (
	context "context"
	_ "embed"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	transport "github.com/not-for-prod/clay/transport"
	httptransport "github.com/not-for-prod/clay/transport/httptransport"
	grpc "google.golang.org/grpc"
)

//go:generate implgen --src order_grpc.pb.go --interface-name OrderServiceServer --dst ../../../.

//go:embed order.swagger.json
var Swagger []byte

// OrderServiceServiceDesc is a descriptor/registrator for the OrderServiceServer.
type OrderServiceServiceDesc struct {
	svc  OrderServiceServer
	opts httptransport.DescOptions
}

// NewOrderServiceServiceDesc creates new registrator for the OrderServiceServer.
// It implements httptransport.ConfigurableServiceDesc as well.
func NewOrderServiceServiceDesc(i OrderServiceServer) *OrderServiceServiceDesc {
	return &OrderServiceServiceDesc{svc: i}
}

// RegisterGRPC implements service registrator interface.
func (d *OrderServiceServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterOrderServiceServer(s, d.svc)
}

// Apply applies passed options.
func (d *OrderServiceServiceDesc) Apply(oo ...transport.DescOption) {
	for _, o := range oo {
		o.Apply(&d.opts)
	}
}

// SwaggerDef returns this file's Swagger definition.
func (d *OrderServiceServiceDesc) SwaggerDef() []byte {
	return Swagger
}

// RegisterHTTP registers this service's HTTP handlers/bindings.
func (w *OrderServiceServiceDesc) RegisterHTTP(
	ctx context.Context,
	mux *runtime.ServeMux,
) error {
	return RegisterOrderServiceHandlerServer(ctx, mux, w)
}

// Wrap all http methods with interceptor support

func (w *OrderServiceServiceDesc) CreateOrder(ctx context.Context, in *CreateOrderRequest) (*CreateOrderResponse, error) {
	if w.opts.UnaryInterceptor == nil {
		return w.svc.CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     w,
		FullMethod: "/order_service.order.v1.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return w.svc.CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	resp, err := w.opts.UnaryInterceptor(ctx, in, info, handler)
	if err != nil || resp == nil {
		return nil, err
	}
	return resp.(*CreateOrderResponse), err
}
