// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api-gateway/order/v1/order.proto

package orderV1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/type/decimal"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state protoimpl.MessageState    `protogen:"open.v1"`
	Order *CreateOrderRequest_Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	// ключ идемпотентности
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// версия списка заказов
	OrdersVersion int64 `protobuf:"varint,3,opt,name=orders_version,json=ordersVersion,proto3" json:"orders_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetOrder() *CreateOrderRequest_Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateOrderRequest) GetOrdersVersion() int64 {
	if x != nil {
		return x.OrdersVersion
	}
	return 0
}

type CreateOrderResponse struct {
	state   protoimpl.MessageState       `protogen:"open.v1"`
	Details *CreateOrderResponse_Details `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	// версия списка заказов
	OrdersVersion int64 `protobuf:"varint,2,opt,name=orders_version,json=ordersVersion,proto3" json:"orders_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetDetails() *CreateOrderResponse_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CreateOrderResponse) GetOrdersVersion() int64 {
	if x != nil {
		return x.OrdersVersion
	}
	return 0
}

type GetActiveOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор клиента
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveOrdersRequest) Reset() {
	*x = GetActiveOrdersRequest{}
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveOrdersRequest) ProtoMessage() {}

func (x *GetActiveOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetActiveOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetActiveOrdersRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GetActiveOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// список заказов
	Orders []*GetActiveOrdersResponse_Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	// слепок состояния (версия)
	OrdersVersion int64 `protobuf:"varint,2,opt,name=orders_version,json=ordersVersion,proto3" json:"orders_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveOrdersResponse) Reset() {
	*x = GetActiveOrdersResponse{}
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveOrdersResponse) ProtoMessage() {}

func (x *GetActiveOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetActiveOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetActiveOrdersResponse) GetOrders() []*GetActiveOrdersResponse_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GetActiveOrdersResponse) GetOrdersVersion() int64 {
	if x != nil {
		return x.OrdersVersion
	}
	return 0
}

type CreateOrderRequest_Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор
	AdId string `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	// Категория
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// Идентификатор клиента
	ClientId string `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Стоимость
	Price         *money.Money `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest_Order) Reset() {
	*x = CreateOrderRequest_Order{}
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest_Order) ProtoMessage() {}

func (x *CreateOrderRequest_Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest_Order.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest_Order) Descriptor() ([]byte, []int) {
	return file_api_gateway_order_v1_order_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateOrderRequest_Order) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *CreateOrderRequest_Order) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateOrderRequest_Order) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateOrderRequest_Order) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

type CreateOrderResponse_Details struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// идентификатор заказа
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// статус заказа
	OrderStatus   string `protobuf:"bytes,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse_Details) Reset() {
	*x = CreateOrderResponse_Details{}
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse_Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse_Details) ProtoMessage() {}

func (x *CreateOrderResponse_Details) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse_Details.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse_Details) Descriptor() ([]byte, []int) {
	return file_api_gateway_order_v1_order_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateOrderResponse_Details) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResponse_Details) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

type GetActiveOrdersResponse_Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// идентификатор заказа
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// статус заказа
	OrderStatus string `protobuf:"bytes,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	// Уникальный идентификатор
	AdId string `protobuf:"bytes,3,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	// Категория
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// Стоимость
	Price         *money.Money `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveOrdersResponse_Order) Reset() {
	*x = GetActiveOrdersResponse_Order{}
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveOrdersResponse_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveOrdersResponse_Order) ProtoMessage() {}

func (x *GetActiveOrdersResponse_Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveOrdersResponse_Order.ProtoReflect.Descriptor instead.
func (*GetActiveOrdersResponse_Order) Descriptor() ([]byte, []int) {
	return file_api_gateway_order_v1_order_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetActiveOrdersResponse_Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetActiveOrdersResponse_Order) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *GetActiveOrdersResponse_Order) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *GetActiveOrdersResponse_Order) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetActiveOrdersResponse_Order) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

var File_api_gateway_order_v1_order_proto protoreflect.FileDescriptor

const file_api_gateway_order_v1_order_proto_rawDesc = "" +
	"\n" +
	" api-gateway/order/v1/order.proto\x12\x14api_gateway.order.v1\x1a\x17google/type/money.proto\x1a\x19google/type/decimal.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xab\x02\n" +
	"\x12CreateOrderRequest\x12D\n" +
	"\x05order\x18\x01 \x01(\v2..api_gateway.order.v1.CreateOrderRequest.OrderR\x05order\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0eorders_version\x18\x03 \x01(\x03R\rordersVersion\x1a\x7f\n" +
	"\x05Order\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12(\n" +
	"\x05price\x18\x06 \x01(\v2\x12.google.type.MoneyR\x05price\"\xd2\x01\n" +
	"\x13CreateOrderResponse\x12K\n" +
	"\adetails\x18\x01 \x01(\v21.api_gateway.order.v1.CreateOrderResponse.DetailsR\adetails\x12%\n" +
	"\x0eorders_version\x18\x02 \x01(\x03R\rordersVersion\x1aG\n" +
	"\aDetails\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x02 \x01(\tR\vorderStatus\"5\n" +
	"\x16GetActiveOrdersRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xb0\x02\n" +
	"\x17GetActiveOrdersResponse\x12K\n" +
	"\x06orders\x18\x01 \x03(\v23.api_gateway.order.v1.GetActiveOrdersResponse.OrderR\x06orders\x12%\n" +
	"\x0eorders_version\x18\x02 \x01(\x03R\rordersVersion\x1a\xa0\x01\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x02 \x01(\tR\vorderStatus\x12\x13\n" +
	"\x05ad_id\x18\x03 \x01(\tR\x04adId\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12(\n" +
	"\x05price\x18\x05 \x01(\v2\x12.google.type.MoneyR\x05price2\x97\x02\n" +
	"\fOrderService\x12u\n" +
	"\vCreateOrder\x12(.api_gateway.order.v1.CreateOrderRequest\x1a).api_gateway.order.v1.CreateOrderResponse\"\x11\x82\xd3\xe4\x93\x02\v\"\t/v1/order\x12\x82\x01\n" +
	"\x0fGetActiveOrders\x12,.api_gateway.order.v1.GetActiveOrdersRequest\x1a-.api_gateway.order.v1.GetActiveOrdersResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x1a\v\x92A\b\n" +
	"\x06ordersBV\x92A1\x12/\n" +
	"\rAdvertisement\x12\x19Advertisement application2\x031.0Z api_gateway/pkg/order/v1;orderV1b\x06proto3"

var (
	file_api_gateway_order_v1_order_proto_rawDescOnce sync.Once
	file_api_gateway_order_v1_order_proto_rawDescData []byte
)

func file_api_gateway_order_v1_order_proto_rawDescGZIP() []byte {
	file_api_gateway_order_v1_order_proto_rawDescOnce.Do(func() {
		file_api_gateway_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_order_v1_order_proto_rawDesc), len(file_api_gateway_order_v1_order_proto_rawDesc)))
	})
	return file_api_gateway_order_v1_order_proto_rawDescData
}

var file_api_gateway_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_gateway_order_v1_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),            // 0: api_gateway.order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),           // 1: api_gateway.order.v1.CreateOrderResponse
	(*GetActiveOrdersRequest)(nil),        // 2: api_gateway.order.v1.GetActiveOrdersRequest
	(*GetActiveOrdersResponse)(nil),       // 3: api_gateway.order.v1.GetActiveOrdersResponse
	(*CreateOrderRequest_Order)(nil),      // 4: api_gateway.order.v1.CreateOrderRequest.Order
	(*CreateOrderResponse_Details)(nil),   // 5: api_gateway.order.v1.CreateOrderResponse.Details
	(*GetActiveOrdersResponse_Order)(nil), // 6: api_gateway.order.v1.GetActiveOrdersResponse.Order
	(*money.Money)(nil),                   // 7: google.type.Money
}
var file_api_gateway_order_v1_order_proto_depIdxs = []int32{
	4, // 0: api_gateway.order.v1.CreateOrderRequest.order:type_name -> api_gateway.order.v1.CreateOrderRequest.Order
	5, // 1: api_gateway.order.v1.CreateOrderResponse.details:type_name -> api_gateway.order.v1.CreateOrderResponse.Details
	6, // 2: api_gateway.order.v1.GetActiveOrdersResponse.orders:type_name -> api_gateway.order.v1.GetActiveOrdersResponse.Order
	7, // 3: api_gateway.order.v1.CreateOrderRequest.Order.price:type_name -> google.type.Money
	7, // 4: api_gateway.order.v1.GetActiveOrdersResponse.Order.price:type_name -> google.type.Money
	0, // 5: api_gateway.order.v1.OrderService.CreateOrder:input_type -> api_gateway.order.v1.CreateOrderRequest
	2, // 6: api_gateway.order.v1.OrderService.GetActiveOrders:input_type -> api_gateway.order.v1.GetActiveOrdersRequest
	1, // 7: api_gateway.order.v1.OrderService.CreateOrder:output_type -> api_gateway.order.v1.CreateOrderResponse
	3, // 8: api_gateway.order.v1.OrderService.GetActiveOrders:output_type -> api_gateway.order.v1.GetActiveOrdersResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_gateway_order_v1_order_proto_init() }
func file_api_gateway_order_v1_order_proto_init() {
	if File_api_gateway_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_order_v1_order_proto_rawDesc), len(file_api_gateway_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_order_v1_order_proto_goTypes,
		DependencyIndexes: file_api_gateway_order_v1_order_proto_depIdxs,
		MessageInfos:      file_api_gateway_order_v1_order_proto_msgTypes,
	}.Build()
	File_api_gateway_order_v1_order_proto = out.File
	file_api_gateway_order_v1_order_proto_goTypes = nil
	file_api_gateway_order_v1_order_proto_depIdxs = nil
}
