// Code generated by xo. DO NOT EDIT.
// Package xo contains the types for schema 'public'.
package xo

import (
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/gofrs/uuid"
)

// Advertisement represents a row from 'public.advertisement'.
type Advertisement struct {
	ID        uuid.UUID `db:"id" json:"id"`                 // id
	Title     string    `db:"title" json:"title"`           // title
	Status    string    `db:"status" json:"status"`         // status
	Category  string    `db:"category" json:"category"`     // category
	AuthorID  uuid.UUID `db:"author_id" json:"author_id"`   // author_id
	Price     float64   `db:"price" json:"price"`           // price
	Version   int       `db:"version" json:"version"`       // version
	CreatedAt time.Time `db:"created_at" json:"created_at"` // created_at
}

// zeroAdvertisement zero value of dto
var zeroAdvertisement = Advertisement{}

// Constants that should be used when building where statements
const (
	Alias_Advertisement            = "a"
	Table_Advertisement_With_Alias = "advertisement AS a"
	Table_Advertisement            = "advertisement"
	Field_Advertisement_ID         = "id"
	Field_Advertisement_Title      = "title"
	Field_Advertisement_Status     = "status"
	Field_Advertisement_Category   = "category"
	Field_Advertisement_AuthorID   = "author_id"
	Field_Advertisement_Price      = "price"
	Field_Advertisement_Version    = "version"
	Field_Advertisement_CreatedAt  = "created_at"
)

func (t Advertisement) SelectColumnsWithCoalesce() []string {
	return []string{
		fmt.Sprintf("COALESCE(a.id, %v) as id", zeroAdvertisement.ID),
		fmt.Sprintf("COALESCE(a.title, '%v') as title", zeroAdvertisement.Title),
		fmt.Sprintf("COALESCE(a.status, '%v') as status", zeroAdvertisement.Status),
		fmt.Sprintf("COALESCE(a.category, '%v') as category", zeroAdvertisement.Category),
		fmt.Sprintf("COALESCE(a.author_id, %v) as author_id", zeroAdvertisement.AuthorID),
		fmt.Sprintf("COALESCE(a.price, %v) as price", zeroAdvertisement.Price),
		fmt.Sprintf("COALESCE(a.version, %v) as version", zeroAdvertisement.Version),
		fmt.Sprintf("COALESCE(a.created_at, '%v') as created_at", zeroAdvertisement.CreatedAt.Format(time.RFC3339)),
	}
}

func (t Advertisement) SelectColumns() []string {
	return []string{
		"a.id",
		"a.title",
		"a.status",
		"a.category",
		"a.author_id",
		"a.price",
		"a.version",
		"a.created_at",
	}
}

func (t Advertisement) Columns(without ...string) []string {
	var str = "id, title, status, category, author_id, price, version, created_at"
	for _, exc := range without {
		str = strings.Replace(str+", ", exc+", ", "", 1)
	}
	return strings.Split(strings.TrimRight(str, ", "), ", ")
}

func (t Advertisement) WithTable(col string) string {
	return fmt.Sprintf("a.%s", col)
}

func (t Advertisement) IsEmpty() bool {
	return reflect.DeepEqual(t, zeroAdvertisement)
}

func (t Advertisement) Join(rightColumnTable string, leftColumnTable string) string {
	return fmt.Sprintf("advertisement AS a ON a.%s = %s", rightColumnTable, leftColumnTable)
}

func (t *Advertisement) ToMap() map[string]interface{} {
	return map[string]interface{}{
		"id":         t.ID,
		"title":      t.Title,
		"status":     t.Status,
		"category":   t.Category,
		"author_id":  t.AuthorID,
		"price":      t.Price,
		"version":    t.Version,
		"created_at": t.CreatedAt,
	}
}

func (t *Advertisement) Values(colNames ...string) (vals []interface{}) {
	m := t.ToMap()
	if _, ok := m["updated_at"]; ok {
		m["updated_at"] = time.Now()
	}

	for _, v := range colNames {
		vals = append(vals, m[v])
	}

	return vals
}
